### ISSUE TITLE
写入host时，出现 gbk 编码错误

### ISSUE THREAD

**Issue by weitanx** [GoodCoder666/GoogleTranslate_IPFinder#1]
系统环境：Windows 10 家庭中文版  22H2  19045.2311
复现步骤：点击 **写入hosts** 时，出现 gbk 编码错误提示
![image](https://user-images.githubusercontent.com/26003285/203288895-488ab271-4b03-4fc2-8bad-f0383aba1221.png)

**Comment by GoodCoder666** [comment]
@weitanx 请问本地Hosts是否有中文字符？

**Comment by weitanx** [comment]
> @weitanx请询问本地Hosts文件是否包含中文字符？

之前 hosts 文件中包含中文注释，现在我把中文注释全部删除后还是会出现 "gbk错误"的提示。
![image](https://user-images.githubusercontent.com/26003285/203312152-b5e6f9c6-8e46-4ae5-89d3-b437f5d8297f.png)

**Comment by GoodCoder666** [comment]
那你在SwitchHosts软件里边的系统Hosts中的第一个红点是什么？UTF-8的文件头？

**Comment by weitanx** [comment]
> witchHosts软件里面的系统Hosts中的第一个红点是什么？UTF-8的文件头？



> 我完全可以配utf-8编码，不过Windows下的HOSTS好象是不能用utf-8的。

我修改了hosts 文件的编码格式为 无 BOM 的 UTF-8，点击 写入hosts 可以正常写入了，但是会出现下列问题
![image](https://user-images.githubusercontent.com/26003285/203366370-d2c235a2-4e68-46d1-8131-0c452fac24d1.png)

**Comment by blog2020** [comment]
我看了一下我的win7系统hosts文件是默认UTF-8格式的

**Comment by GoodCoder666** [comment]
@weitanx 对于空行的问题，我个人建议你试试把整个HOSTS文件全部清空然后再写入

如果hosts中已有谷歌翻译的host，程序默认是会替换掉原来设置的IP，但谷歌翻译的host在文件中的位置不变。

**Comment by GoodCoder666** [comment]
@weitanx 对于空行的问题，我个人建议你试试把整个HOSTS文件全部清空然后再写入

如果hosts中已有谷歌翻译的host，程序默认是会替换掉原来设置的IP，但谷歌翻译的host在文件中的位置不变。

还有，正常就是写入第一个IP，为了访问速度不会写入多个IP（后面可能会考虑加个选项供用户自行设置）。

**Comment by weitanx** [comment]
> @weitanx针对空行的问题，我个人建议你试把整个HOSTS文件全部清空然后重新写入
> 
> 如果hosts中已有谷歌翻译的host，程序默认认为会替换掉原始设置的IP，但谷歌翻译的host在文件中的位置不变。
> 
> 还有，正常就是写入第一个IP，为了访问速度不会写入多个IP（后面可能会考虑添加一个选项供用户自行设置）。

前提条件： 已下载更新为最新版本，hosts 文件内容已清空

存在问题： 在hosts 文件内容已清空的前提下，
		  第一次点击 "写入hosts"按钮 会从第三行开始写入，紧接着会出现第4、5空行

		  从第二次开始 每点击一次 "写入hosts"按钮，（如果hosts中已有谷歌翻译的host，程序默认认为会替换掉原始设置的IP，但谷歌翻译的host在文件中的位置不变）括号中的内容正常执行的前提下，都会追加一个新的空行
![动画](https://user-images.githubusercontent.com/26003285/203564508-e391c899-2d68-413f-9562-28313fd22451.gif)

**Comment by jingjingxyk** [comment]
写入文件，就让用户自己操作就好了，无非是粘贴、复制、保存罢了。

软件帮他把host文件打开和准备域名解析列表就好


学会修改hosts的用户，动手能力并不差

**Comment by GoodCoder666** [comment]
@jingjingxyk 感谢分享

@weitanx 现在编码问题已经解决了，我专门开了一个新的issue #4 来解决空行问题，大家可以到那里去讨论。
