### ISSUE TITLE
无法使用，  运行ggc  出现报错。

### ISSUE THREAD

**Issue by ezraliyzh** [GoodCoder666/GoogleTranslate_IPFinder#12]
internal/modules/cjs/loader.js:797
    throw err;
    ^

Error: Cannot find module 'node:fs/promises'
Require stack:
- C:\Users\Ezrali\AppData\Roaming\npm\node_modules\@hcfy\check-google-translate-ip-cli\dist\index.js
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:687:27)[39m
[90m    at Module.require (internal/modules/cjs/loader.js:849:19)[39m
[90m    at require (internal/modules/cjs/helpers.js:74:18)[39m
    at Object.<anonymous> (C:\Users\Ezrali\AppData\Roaming\npm\node_modules\[4m@hcfy[24m\check-google-translate-ip-cli\dist\index.js:8:36)
[90m    at Module._compile (internal/modules/cjs/loader.js:956:30)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:812:32)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:724:14)[39m
[90m    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: [
    [32m'C:\\Users\\Ezrali\\AppData\\Roaming\\npm\\node_modules\\@hcfy\\check-google-translate-ip-cli\\dist\\index.js'[39m
  ]
}

**Comment by GoodCoder666** [comment]
此问题请在 https://github.com/hcfyapp/google-translate-cn-ip 提出
