### ISSUE TITLE
写入Hosts后依然无法访问Google翻译

### ISSUE THREAD

**Issue by HoeYeungHo** [GoodCoder666/GoogleTranslate_IPFinder#13]
我使用GoogleTranslate_IPFinder扫描了IP并将结果写入了Hosts文件中（142.250.99.121 translate.googleapis.com）。

我在浏览器中无法访问translate.googleapis.com，访问142.250.99.121显示：The requested URL / was not found on this server.

使用PING translate.googleapis.com提示「请求找不到主机」，使用PING 142.250.99.121可以正常连接（平均 = 224ms）。

请问我应该如何修复才能够正常访问Google翻译？

**Comment by GoodCoder666** [comment]
我刚修复了一个bug，解决了扫描/测速结果不正确的问题。过一会会提交代码并发布新版。

**Comment by dddddgz** [comment]
bug现在还有，并且应该写入的是 translate.google.com

**Comment by GoodCoder666** [comment]
> bug现在还有，并且应该写入的是 translate.google.com

您可能理解错我的意思了，这个项目是用来修复 **谷歌翻译 API**（`translate.googleapis.com`）的，目前修改 hosts 无法实现正常访问谷歌翻译网页版。修复 API 可以使基于谷歌翻译的插件（Google 翻译、划词翻译等）可用。
