### ISSUE TITLE
可以放开自定义域名吗？

### ISSUE THREAD

**Issue by wuzhengzheng** [GoodCoder666/GoogleTranslate_IPFinder#14]
好多时候GitHub比较慢，我想也可以用这个工具进行修复

**Comment by AjianYo** [comment]
好想法！

**Comment by GoodCoder666** [comment]
如果想要加速 GitHub 可以用 GitHub520 项目（我也contribute过）

但是 github 这种网站的 ip 不会很多，可以上 ipaddress 查一下，最多四五个，也没必要自动化

**Comment by AjianYo** [comment]
> 如果想要加速 GitHub 可以用 GitHub520 项目（我也contribute过）
> 
> 但是 github 这种网站的 ip 不会很多，可以上 ipaddress 查一下，最多四五个，也没必要自动化

是的，GitHub意义不大，但是“自定义域名”未来有可能支持吗？

**Comment by GoodCoder666** [comment]
绝大部分网站都只有1-2个服务器，github算多的了
