### ISSUE TITLE
可不可以也做一个谷歌的其他页面的访问啊

### ISSUE THREAD

**Issue by dddddgz** [GoodCoder666/GoogleTranslate_IPFinder#15]
![Snipaste_2023-06-13_23-21-42](https://github.com/GoodCoder666/GoogleTranslate_IPFinder/assets/134162766/d2a23cdb-aac6-4005-905a-7269f0deb807)
（用了你的之后就可以访问translate.google.com了）
我想知道为什么你搞到的ip ping一下是一致的，我的ip即使一致也不能访问？
![Snipaste_2023-06-13_23-25-25](https://github.com/GoodCoder666/GoogleTranslate_IPFinder/assets/134162766/66fcae52-d397-436f-b85b-7d0d4e5d405a)
可否再做一个呀

**Comment by GoodCoder666** [comment]
> 我想知道为什么你搞到的ip ping一下是一致的，我的ip即使一致也不能访问？

没有完全懂您的意思，能解释一下吗？

**Comment by dddddgz** [comment]
> > 我想知道为什么你搞到的ip ping一下是一致的，我的ip即使一致也不能访问？
> 
> 没有完全懂您的意思，能解释一下吗？

谢谢！本来以为不会回复的

我的意思是为什么你的程序运行起来，ping得到的ip和hosts文件里的一致，但我自己加的Youtube就不能访问

**Comment by GoodCoder666** [comment]
抱歉让您久等了。

如果 Hosts 中加入 IP 后仍不能访问 YouTube，则**此 IP 是无效的**。

> 理论上，中国大陆地区不存在任何针对 Google 主站或 YouTube 的有效 IP。

解释一下原理：加入 Hosts 中的作用就是相当于代替了 [DNS 解析](https://baike.baidu.com/item/%E5%9F%9F%E5%90%8D%E7%B3%BB%E7%BB%9F/2251573)。如果一个网站直接访问不了，说明 DNS 解析到的 IP 由于某些原因无法访问。本工具的原理就是从海量的 IP 中找到能正常访问的并写入 Hosts，这样正常访问谷歌翻译时就会自动使用可用的 IP。

**Comment by dddddgz** [comment]
> 抱歉让您久等了。
> 
> 如果 Hosts 中加入 IP 后仍不能访问 YouTube，则**此 IP 是无效的**。
> 
> > 理论上，中国大陆地区不存在任何针对 Google 主站或 YouTube 的有效 IP。
> 
> 解释一下原理：加入 Hosts 中的作用就是相当于代替了 [DNS 解析](https://baike.baidu.com/item/%E5%9F%9F%E5%90%8D%E7%B3%BB%E7%BB%9F/2251573)。如果一个网站直接访问不了，说明 DNS 解析到的 IP 由于某些原因无法访问。本工具的原理就是从海量的 IP 中找到能正常访问的并写入 Hosts，这样正常访问谷歌翻译时就会自动使用可用的 IP。

谢谢！您的意思是 hosts 会更改 dns 解析，也就是说我 ping 到的 google translate ip 是事先准备好的，放在您的程序里。

那哪里可以得到没有被污染的 google ip？

**Comment by GoodCoder666** [comment]
谷歌的ip应该是都没法用，只能用梯子之类的

**Comment by dddddgz** [comment]
> @GoodCoder666 @dddddgz
> 
> > 理论上，中国大陆地区不存在任何针对 Google 主站或 YouTube 的有效 IP。
> 
> 该软件扫描出的IP都是GWS，可以提供除YouTube视频之外的大部分Google服务。直接加入hosts里没有用是因为GFW的SNI阻断。
> 
> 你把它加入剔除SNI的本地代理工具中就能访问了。 https://github.com/URenko/Accesser 。

谢谢回答

**Comment by UjuiUjuMandan** [comment]
@dddddgz 忘了说了，剔除SNI是错的，因为GWS不支持无SNI连接，应该是在该工具的 alter_hostname 指定伪装SNI。比如

```
"www.google.com.hk" = "www.google.cn"
"www.youtube.com" = "www.google.cn"
```

**Comment by Homo-Vexillues** [comment]
> @dddddgz 忘了说了，剔除SNI是错的，因为GWS不支持无SNI连接，应该是在该工具的配置文件的 alter_hostname 指定伪装SNI。比如
> 
> ```
> "www.google.com.hk" = "www.google.cn"
> "www.youtube.com" = "www.google.cn"
> ```

请问其他服务也是这样吗，像我在使用的这些都是改成.cn结尾吗？
47.102.115.14 translate.googleapis.com
47.102.115.14 translate-pa.googleapis.com
47.102.115.14 translate.google.com
47.102.115.14 translation.google.com
47.102.115.14 www.google.com
47.102.115.14 accounts.google.com
47.102.115.14 chrome.google.com
47.102.115.14 chromewebstore.google.com

**Comment by Homo-Vexillues** [comment]
> 你用的啥？SNI需要变为 .cn，HTTP Host不变。

大佬是这样的，我是个刚学计算机的清澈大学牲:D
原本我在用666大佬的翻译IP测速工具，后来发现谷歌的实时字幕的实时翻译网址是translation.google.com（我们校园网时不时能用谷歌服务，甚至reddit和quora偶尔也能行），为了稳定使用这个功能就把这个网址加在了测速工具里，

**Comment by GoodCoder666** [comment]
@UjuiUjuMandan 您觉得有没有必要做一个测速/扫描时可以指定 SNI 的选项？

**Comment by GoodCoder666** [comment]
差点忘了，现在设置里的 `域名` 选项指定的就是 SNI 😆 如果有需要改也可以试试

这里只会更改测速/扫描设置，**不会影响本地的全局设置**。
