### ISSUE TITLE
你好，mac os Ventura 13使用不了

### ISSUE THREAD

**Issue by soukicn** [GoodCoder666/GoogleTranslate_IPFinder#17]
大佬，你好，请教一下为何在mac下无法使用？
测速时总是显示urlopen error time out，第一遍是urlopen error [SSL: CERTIFICATE_VERIFY_FAILED]
不知道应该如何解决？谢谢。系统是13.5.1

**Comment by GoodCoder666** [comment]
我认为应该不是系统的问题，而是网络环境的问题。
如果系统有问题一般是整个程序直接运行不了。

您可以检查一下是否有错误设置代理，或者使用了公司/学校网络导致所有 IP 都不可用？

**Comment by soukicn** [comment]
好的，谢谢回复。使用的就是家里的网络，更换了手机作为热点，还是问题依旧。不知道原因是什么，我再搜搜看。谢谢。

**Comment by cced3000** [comment]
一样的问题，也是不能用，一样的报错

**Comment by HaveF** [comment]
我也遇到了，看代码应该是 SSL 证书的问题

https://cloud.tencent.com/developer/ask/sof/113134118
https://blog.csdn.net/yangxiaodong88/article/details/80757383

这里可能得改下
https://github.com/GoodCoder666/GoogleTranslate_IPFinder/blob/e63cc3be53bfeb68d4ec08fd5b761fb401aa99ef/utils.py#L34

**Comment by GoodCoder666** [comment]
@HaveF 感谢指出，已修改，还得请您帮忙测试一下能否正常使用（手头没有 Mac 电脑 🤣 ）

**Comment by HaveF** [comment]
@GoodCoder666 works! 可以发包啦！

**Comment by GoodCoder666** [comment]
问题已解决：https://github.com/GoodCoder666/GoogleTranslate_IPFinder/releases/tag/v1.12.2
