### ISSUE TITLE
写入Hosts时添加注释

### ISSUE THREAD

**Issue by izwb003** [GoodCoder666/GoogleTranslate_IPFinder#2]
![图片](https://user-images.githubusercontent.com/29999036/203777349-2ab78214-95cf-46aa-9a2b-682c373c8c9a.png)

如图。是否考虑像图中所示方式，在添加IP时前后添加一条注释，表明该条目是用于重定向Google Translate的？我看到一些需要修改Hosts的软件及一些Hosts项目一般都会采用这样的格式来方便区分不同的条目，这样的写入方式或许也很有助于Hosts中有多条内容的朋友来方便查找不同条目，防止混淆。

谢谢。

**Comment by GoodCoder666** [comment]
可以，不过没必要。这种Start+End的注释形式一般适用于多条Host的写入，单条Host没有必要使用这种注释。不过下面这种方式应该是可行的：
```
142.250.4.163 translate.googleapis.com # Google Translate Redirect Host
```

**Comment by izwb003** [comment]
> 可以，不过没必要。这种Start+End的注释形式一般适用于多条Host的写入，单条Host没有必要使用这种注释。不过下面这种方式应该是可行的：
> 
> ```
> 142.250.4.163 translate.googleapis.com # Google Translate Redirect Host
> ```
> 
> 如果各位觉得可以的话，我就来做这个功能

也是不错的做法。我主要在想对于经常修改Hosts的朋友，他们的Hosts条目中或许多为Start+End的注释格式，也采用Start+End注释或许格式更统一。

**Comment by GoodCoder666** [comment]
是的。不过这样在代码逻辑中会有一些麻烦，比如如下的HOSTS文件：
```
142.250.4.163 translate.googleapis.com

# Google Translate Redirect Start
142.250.4.163 translate.googleapis.com
# Google Translate Redirect End
```
这种情况程序应该怎么处理？类似的问题还有很多。

**Comment by mfkps** [comment]
多次测速后
Error: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
出现些错误，怎么解决？
