### ISSUE TITLE
程序无权限写入

### ISSUE THREAD

**Issue by Aiopre** [GoodCoder666/GoogleTranslate_IPFinder#22]
![error1](https://github.com/GoodCoder666/GoogleTranslate_IPFinder/assets/131159305/98d4f7b9-6800-402f-bd02-8872293f95e7)

**Comment by GoodCoder666** [comment]
用管理员权限打开再试试

**Comment by Aiopre** [comment]
一直都是管理员打开，都是无权限。刚刚重启了一下就好了，已解决

**Comment by Aiopre** [comment]
> 用管理员权限打开再试试


https://github.com/GoodCoder666/GoogleTranslate_IPFinder/assets/131159305/bab3c0a2-6665-43f3-bbaf-5df2a7c1f52f

**Comment by Aiopre** [comment]
~~ ~~ok

**Comment by Aiopre** [comment]
~~我是大笨蛋~~
发现是hosts文件权限不知道为什么有时候会设置成只读。在我重启10次中，有8次勾选了只读，2次竟然没有勾选只读，我不知道我的电脑咋了？！
