### ISSUE TITLE
翻译地址可能已更换

### ISSUE THREAD

**Issue by FanJZSS** [GoodCoder666/GoogleTranslate_IPFinder#24]
最近使用内核102的百分浏览器在hosts加入`translate.googleapis.com`已无法不挂梯翻译，查看clash日志发现一个`translate-pa.googleapis.com`，添加到hosts后可以正常不挂梯翻译

**Comment by GoodCoder666** [comment]
大概率是浏览器的问题。实测Chrome默认还是使用`translate.googleapis.com`，主流翻译插件也可正常工作。

**Comment by GoodCoder666** [comment]
抱歉，确实是我之前的错误，欢迎到 #27 关注处理进展。
