### ISSUE TITLE
能否加入随机IP扫描或者指定IP组扫描

### ISSUE THREAD

**Issue by neariver** [GoodCoder666/GoogleTranslate_IPFinder#25]
每次扫描都先扫开头那扫那几个IP几段IP，只要十几个的IP，后面有些IP都没机会扫到，能否加入一个功能选项，能选全部随机IP扫描或者指定IP组扫描，不用每次都只扫开头那几个IP

**Comment by GoodCoder666** [comment]
我先加了随机化扫描，自定义扫描IP段还在考虑怎么做

1.13 Alpha 已发布，可以先试试。
