### ISSUE TITLE
写入 Hosts 时同时处理 translate-pa.googleapis.com

### ISSUE THREAD

**Issue by jianan46** [GoodCoder666/GoogleTranslate_IPFinder#27]
复制功能只复制了translate.googleapis.com这个域名，然而在实际使用时翻译没有成功，抓包看到translate.google.com和translate-pa.googleapis.com两个域名也有接口调用，在添加这两个域名后，翻译功能可以正常使用了，所以是否有必要同时添加以上两个域名？
![D-Chat_20240320164040](https://github.com/GoodCoder666/GoogleTranslate_IPFinder/assets/52652670/41ff872b-6d6f-4b4b-969e-91c4696c4b2a)
![D-Chat_20240320164058](https://github.com/GoodCoder666/GoogleTranslate_IPFinder/assets/52652670/383eef8f-a441-4ddf-8db8-5a4949816cce)

**Comment by GoodCoder666** [comment]
你那边用的什么软件？只写入 `translate.googleapis.com` 就能修复多数主流软件翻译功能

**Comment by jianan46** [comment]
> 你那边用的什么软件？只写入 `translate.googleapis.com` 就能修复多数主流软件翻译功能

就是chrome版本 123.0.6312.59（正式版本） (arm64)

**Comment by yutao7777** [comment]
> 复制功能只复制了translate.googleapis.com这个域名，然而在实际使用时翻译没有成功，抓包看到translate.google.com和translate-pa.googleapis.com两个域名也有接口调用，在添加这两个个域名后，翻译功能可以正常使用了，那么是否有必要同时添加以上两个域名？ ![D-Chat_20240320164040](https://private-user-images.githubusercontent.com/52652670/314429435-41ff872b-6d6f-4b4b-969e-91c4696c4b2a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyMjgxNDUsIm5iZiI6MTcxMjIyNzg0NSwicGF0aCI6Ii81MjY1MjY3MC8zMTQ0Mjk0MzUtNDFmZjg3MmItNmQ2Zi00YjRiLTk2OWUtOTFjNDY5NmM0YjJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA0VDEwNTA0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlNGEyNWNlNGRlOWI0YzBhMWQ1Y2FjZWNlMzk3Y2RlYTgwN2FlMTdjMDQ4MTgwYWJhMDY0OTJkZTkwZjgxZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jyHtLPTABHEvZjgTTCf5U2PnZWEjtowqX0wprHbAi2U) ![D-Chat_20240320164058](https://private-user-images.githubusercontent.com/52652670/314429563-383eef8f-a441-4ddf-8db8-5a4949816cce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyMjgxNDUsIm5iZiI6MTcxMjIyNzg0NSwicGF0aCI6Ii81MjY1MjY3MC8zMTQ0Mjk1NjMtMzgzZWVmOGYtYTQ0MS00ZGRmLThkYjgtNWE0OTQ5ODE2Y2NlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA0VDEwNTA0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjNGY2YTU5MGU3YzdjYWVkYjU1MzFiZGQ2YWEzZmFjNjhhMjZkOGIxMWExODljYjM2MGY1ZTBhOWRlODUzZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.c09jy6_Zs-jfzavTvgcRRgiq2EYBjVmV5FASyQSgPUY)

感谢，多加了两个链接就可以用了

**Comment by snakexgc** [comment]
大佬可以考虑设置一个自定义修改host域名列表，这样用户可以按需自行修改，我也遇到了只修改translate.googleapis.com不能翻译的情况，感觉这项功能可以考虑增加一下。

**Comment by GoodCoder666** [comment]
看来这个功能需求量不小，我去实现一下 🤣

**Comment by GoodCoder666** [comment]
来试试新版的 1.14.0？本地测试通过

还有 `translate.google.com` 这个我不确定要不要加，好像加了也用不了网页版

**Comment by jianan46** [comment]
我今天试了一下，我是用的mac，不能直接通过你的软件写入host，手动复制的话只是复制了translate.googleapis.com这个域名，结果也并不能成功翻译，需要手动添加translate-pa.googleapis.com才可以正常翻译。

**Comment by GoodCoder666** [comment]
> 我今天试了一下，我是用的mac，不能直接通过你的软件写入host，手动复制的话只是复制了translate.googleapis.com这个域名，结果也并不能成功翻译，需要手动添加translate-pa.googleapis.com才可以正常翻译。

@jianan46 新版会复制pa域名了，请验证

**Comment by jianan46** [comment]
[1.14.1]版本确实可以复制pa域名，我测试了没问题，但是我用不了写入host功能，不确定这个功能有没有问题，如果没问题的话我就关掉这个issues了

**Comment by snakexgc** [comment]
> [1.14.1]版本确实可以复制pa域名，我测试了没问题，但是我用不了写入host功能，不确定这个功能有没有问题，如果没问题的话我就关掉这个issues了
记得看一下host文件权限是不是只读，win默认就是只读，只读情况下管理员权限也不能写入，上次我就被这个坑了

**Comment by snakexgc** [comment]
@GoodCoder666 个人觉得不停的加入新的域名不是一个很好的解决办法，希望能够直接增设一个自定义域名列表 #30

**Comment by jianan46** [comment]
> > [1.14.1]版本确实可以复制pa域名，我测试了没问题，但是我用不了写入host功能，不确定这个功能有没有问题，如果没问题的话我就关掉这个issues了
> 
> 记得看一下host文件权限是不是只读，win默认就是只读，只读情况下管理员权限也不能写入，上次我就被这个坑了

确实是文件只读问题，我修改了文件权限，可以使用写入功能了，感谢！

**Comment by GoodCoder666** [comment]
> 个人觉得不停的加入新的域名不是一个很好的解决办法，希望能够直接增设一个自定义域名列表 #30

@snakexgc ok的，不过这个需要一定规模的重构，做好之后会把各种参数的自定义功能一起加进来

**Comment by GoodCoder666** [comment]
我把类似的需求都整合到 #36 了，欢迎提出意见。

**Comment by myunco** [comment]
> 来试试新版的 1.14.0？本地测试通过
> 
> 还有 `translate.google.com` 这个我不确定要不要加，好像加了也用不了网页版

加吧，我一直都加的，反正我这边加了这个之后可以正常使用网页版谷歌翻译
