### ISSUE TITLE
win10以管理员身份启动后仍然不能正常写入host

### ISSUE THREAD

**Issue by snakexgc** [GoodCoder666/GoogleTranslate_IPFinder#28]
win 10
![image](https://github.com/GoodCoder666/GoogleTranslate_IPFinder/assets/78722169/7820e288-d0d1-4b9c-bf22-e9fe1d472abc)
软件是最新的 1.13.0 版本
以管理员身份启动软件仍然不能正常写入host
![image](https://github.com/GoodCoder666/GoogleTranslate_IPFinder/assets/78722169/b992d10f-b5a7-41f0-bd94-e053b9ddfe90)
![image](https://github.com/GoodCoder666/GoogleTranslate_IPFinder/assets/78722169/829f45b6-51ad-4b6f-a43d-548ba943e221)
希望大佬能够修复一下！

**Comment by GoodCoder666** [comment]
先检查一下hosts文件是否为只读？
