### ISSUE TITLE
建议在扫描过程中将扫描按键变更为停止按键

### ISSUE THREAD

**Issue by Drc0rp** [GoodCoder666/GoogleTranslate_IPFinder#29]
如题目所说，现在程序一旦开始扫描，软件就无法进行任何操作。包括无法停止，若要停止只能强制退出。
希望在扫描开始后把扫描按键变更为停止按键。

**Comment by GoodCoder666** [comment]
感谢建议，已提交更改

**Comment by GoodCoder666** [comment]
现在可以验证最新的 1.14.0 是否达到预期效果 @Drc0rp
