### ISSUE TITLE
是否考虑其他网址

### ISSUE THREAD

**Issue by Klein-mrz** [GoodCoder666/GoogleTranslate_IPFinder#3]
比如说允许用户输入网址去找能访问的IP?

**Comment by Klein-mrz** [comment]
以及单条ip导入host

**Comment by GoodCoder666** [comment]
> 比如说允许用户输入网址去找能访问的IP?

理论上不行。比如扫描谷歌翻译的IP，是在谷歌专门的IP网络中进行扫描的。而对于一个不固定的网址，很难确定可用的IP范围。

> 以及单条ip导入host

这个在 #1 中已经有人提出过，最好新开一个issue解决此问题
