### ISSUE TITLE
翻译不起作用，解析URL被指向了translate-pa.googleapis.com

### ISSUE THREAD

**Issue by li9633** [GoodCoder666/GoogleTranslate_IPFinder#31]
## 问题描述
通过抓包查看了一下翻译的域名，发现有时候会指向**translate-pa.googleapis.com**这个URL
![屏幕截图 2024-04-20 171035](https://github.com/GoodCoder666/GoogleTranslate_IPFinder/assets/67550161/79d8fc42-2ba6-4776-a2b2-5aa1e6d51a75)

把这个URL添加到hosts文件里面，翻译功能就正常了
## 疑问
但问题是为什么会指向这个URL，通常情况下应该指向**translate.googleapis.com**这个URL
## 排查
我查询了一下**translate-pa.googleapis.com**解析的IP，发现解析的结果是中国台湾谷歌云。但很巧的是，我的Windows区域设置在之前更改成了中国台湾，我尝试更改为中国，**似乎**不再指向**translate-pa.googleapis.com**了，过了一会又开始指向**translate-pa.googleapis.com**
![屏幕截图 2024-04-20 164652](https://github.com/GoodCoder666/GoogleTranslate_IPFinder/assets/67550161/c1dd7bb3-b770-4f4d-9775-4cf7c1093990)

![屏幕截图 2024-04-20 165030](https://github.com/GoodCoder666/GoogleTranslate_IPFinder/assets/67550161/f28d3f3b-9ebb-4381-b59b-06132e1881bb)

## 解决方案
我怀疑和Windows的区域设置有关，但无法准确的复现，所以目前唯一的解决方案就是将**translate-pa.googleapis.com**这个URL添加到hosts文件里

可以将两个URL同时写到hosts里 #27

**Comment by GoodCoder666** [comment]
感谢，这个问题会在 #27 中统一处理。
