### ISSUE TITLE
大佬 功能请求

### ISSUE THREAD

**Issue by Awe7** [GoodCoder666/GoogleTranslate_IPFinder#32]
大佬能搞个网页的host文件嘛包含一些谷歌翻译的域名，就像是  GitHub  520  这个项目一样，每日更新一次可用IP ，然后其他方式部署dns 返代或直接写入，host  . 岂不是 yyds !!

**Comment by GoodCoder666** [comment]
> Win10系统每次扫码都要跑100％才会自动停止吗？

可以在扫描开始前设置最大IP数，扫出超过指定数量就会自动停止。
