### ISSUE TITLE
请考虑添加translate.brave.com的可用IP扫描

### ISSUE THREAD

**Issue by qcxiang** [GoodCoder666/GoogleTranslate_IPFinder#33]
请考虑添加translate.brave.com的可用IP扫描

**Comment by GoodCoder666** [comment]
扫描必须先确定IP段，后续会考虑添加自定义域名+IP段的扫描功能。

**Comment by Homo-Vexillues** [comment]
@GoodCoder666 大佬，请问一下您知道谷歌实时字幕的翻译是走的哪里吗？
我把https://translate.googleapis.com/，https://translate-pa.googleapis.com/和https://translate.google.com/都写了，api翻译和网页翻译都可以正常使用，但是实时字幕的翻译还是用不了QAQ

**Comment by GoodCoder666** [comment]
@Homo-Vexillues 这个我也不知道，用 Wireshark 之类的工具抓包试试吧 🤣

**Comment by Homo-Vexillues** [comment]
> @Homo-Vexillues 这个我也不知道，用 Wireshark 之类的工具抓包试试吧 🤣

之前找到了，是translation.googleapis.com，加进去就行了
