### ISSUE TITLE
大佬我发现这个软件很百搭，希望能添加自定义调试地址，瞬间把可用性拉高。

### ISSUE THREAD

**Issue by 1994JOE** [GoodCoder666/GoogleTranslate_IPFinder#35]
大佬我发现这个软件很百搭，希望能添加自定义调试地址，瞬间把可用性拉高。
IP我们可以自己找，只需要添加自定义固定地址和保存地址。希望大佬后面可以采纳，感谢与期待。

**Comment by GoodCoder666** [comment]
我把类似的需求都整合到 #36 了，欢迎提出意见。
