### ISSUE TITLE
2.0.0a0版的重置设置的bug

### ISSUE THREAD

**Issue by neariver** [GoodCoder666/GoogleTranslate_IPFinder#37]
2.0.0a0版左上角选项的的重置设置，一旦点了就再也无法进入设置，再点设置就没反应

**Comment by GoodCoder666** [comment]
用的什么操作系统？

**Comment by neariver** [comment]
win11

> 用的什么操作系统？

**Comment by GoodCoder666** [comment]
@neariver  我又测试了一遍，没问题的呀，方便从源代码运行看一下报错信息吗？

**Comment by neariver** [comment]
> @neariver 我又测试了一遍，没问题的呀，方便从源代码运行看一下报错信息吗？

我是小白用户不知道怎样从源代码运行

**Comment by GoodCoder666** [comment]
你试一下用 cmd 运行 exe 文件呢

大概就是这样

```
Microsoft Windows [版本 10.0.22631.3880]
(c) Microsoft Corporation。保留所有权利。

C:\Users\stanl\Downloads> checker-win-x64.exe
[操作之后把这里的输出发给我]
```

**Comment by neariver** [comment]
我试了没有东西显示出来
我拿去另外一台电脑试没问题，我知道是什么引起的，出问题那个我在设置里换了主题换成window那个复古，点击重置设置，再点设置就没反应了，再也换不回主题

**Comment by GoodCoder666** [comment]
问题找到了，正在修复

**Comment by GoodCoder666** [comment]
@neariver 你测试一下 [2.0.0 正式版](https://github.com/GoodCoder666/GoogleTranslate_IPFinder/releases/download/v2.0.0/checker-win-x64.exe)，看看问题还存在吗？

**Comment by neariver** [comment]
2.0.0 正式版可以了
还有选项那个设置我刚开始还以为是扫描的设置，原来时测速的设置，如果整合下就好了

**Comment by GoodCoder666** [comment]
扫描的设置还没做好，可以关注 #36
