### ISSUE TITLE
translate

### ISSUE THREAD

**Issue by petropaak** [GoodCoder666/GoogleTranslate_IPFinder#38]
hi please translate all button and label to english

**Comment by GoodCoder666** [comment]
Thanks for the feedback! I'll try to do it when I have time later.

Meanwhile, as the project targets Mainland China users, could you explain how it is being utilized overseas? Maybe I'll include some useful features based on your reply in future versions.

**Comment by GoodCoder666** [comment]
I'm not sure about that, but is Google Translate not working in Iran without the tool?

**Comment by petropaak** [comment]
Yes, I just put the IPs in the hosts file
Previously, we used to add a repaired transliteration in Potplayer, but it also failed, Imam, now it is fixed with your program.

**Comment by GoodCoder666** [comment]
OK that's wonderful. Try the first button on the right (text including "hosts"), it will automatically modify the hosts file with the fastest responding IP (requires admin privileges).

It might take quite a while for the translation as I'm busy at the period. Thanks for understanding.

**Comment by petropaak** [comment]
It didn't work with admin access either and I had to enter the pinged IP(win 10) manually.thanks

**Comment by GoodCoder666** [comment]
Hi @petropaak 

I just finished all the translations and release a preview. Check them out:

1. Download pre-release [2.1.0](https://github.com/GoodCoder666/GoogleTranslate_IPFinder/releases/tag/v2.1.0)
2. Start the new app. It should automatically switch to English on non-Chinese systems.

If you encounter any issues feel free to report them here.

(English README will be ready later)

**Comment by GoodCoder666** [comment]
English README is up: https://github.com/GoodCoder666/GoogleTranslate_IPFinder/blob/main/README.en.md

**Comment by GoodCoder666** [comment]
@petropaak As the translations are done by now, this issue shall be closed. You can open another issue if the "update hosts" feature does not work for you. Thanks 😄

**Comment by petropaak** [comment]
Hello, sorry for my late reply
Thank you for translating the program
It works properly
Wishing you more success
