### ISSUE TITLE
ip段扫描

### ISSUE THREAD

**Issue by theFreeWall** [GoodCoder666/GoogleTranslate_IPFinder#40]
目前所有ip均已阻断，是否可以增加ip段扫描？试了一下只能单ip
如扫描34.142.128.0/17的ip范围
https://github.com/lord-alfred/ipranges/blob/main/google/ipv4.txt

**Comment by GoodCoder666** [comment]
增加 IP 段的功能预计随自定义 IP 段一起发布，届时将会支持选择要扫描的 IP 段（会提供一个完整的表）。

**Comment by GoodCoder666** [comment]
增加 IP 段的功能预计随自定义 IP 段一起发布，届时会支持选择要扫描的 IP 段（会提供一个完整的表）。

**Comment by theFreeWall** [comment]
谢谢!

**Comment by GoodCoder666** [comment]
@theFreeWall 欢迎测试带自定义 IP 段功能的 2.3.0 版本！
