### ISSUE TITLE
咨询一个关于扫描的问题

### ISSUE THREAD

**Issue by LickJon** [GoodCoder666/GoogleTranslate_IPFinder#43]
咨询一个关于扫描的问题：
扫描IP很多时候一条结果都没有。貌似在扩展IP被更新后才会继续扫出结果。是巧合还是软件的设置问题呢？如果是基于扩展IP段规则进行扫描。希望能自定义扫描的IP段。因为可用IP大多数比较集中。最近不知道为什么，失效非常快，以前一个能用几个月，现在可能撑不过几个小时。如果扫不出结果，那就得傻眼几天。

**Comment by GoodCoder666** [comment]
感谢反馈。自定义扫描 IP 段功能还在开发中，由于本人暂时较忙，距正式发布还要一段时间（参见 #36 ）。

IP 的可用性问题见 #42 。

**Comment by GoodCoder666** [comment]
在功能正式推出之前，可以仿照原有的格式更改 IPv6 扫描段并从源代码运行。

https://github.com/GoodCoder666/GoogleTranslate_IPFinder/blob/7ad39a54d7050f8e8497521ead8c6699971cfa86/threads.py#L100-L104

**Comment by GoodCoder666** [comment]
功能已发布，见 2.3.0。
