### ISSUE TITLE
2.3.0 运行有问题，报错

### ISSUE THREAD

**Issue by LickJon** [GoodCoder666/GoogleTranslate_IPFinder#45]
错误信息：Failed to extract entry: PySide6\Qt6Gui.dll.

**Comment by GoodCoder666** [comment]
请提供一下操作系统信息

以下系统测试通过
```
版本	Windows 11 专业版
版本号	23H2
安装日期	‎2023/‎3/‎23
操作系统版本	22631.4541
体验	Windows 功能体验包 1000.22700.1055.0
```

**Comment by GoodCoder666** [comment]
问题在虚拟机上无法复现

![image](https://github.com/user-attachments/assets/bb02756b-dfaa-4c43-82b7-0c03a0852328)

**Comment by LickJon** [comment]
重新下载可以了。谢谢。希望再增加一个自动保存功能。设置多个IP段扫描的时候。因为是远程机子挂机扫，有时候线程多或者其他原因扫的太猛导致导致网络中断。又连不上远程机器了，只能重启机子。已经扫描的就得重新来过。如果能加个扫描过程中自动保存扫描出来的结果就更好了。另外大佬能教一下取IP段的技巧吗？盲扫好像命中率很低。再次感谢大佬。

**Comment by GoodCoder666** [comment]
最近可用IP较少，目前还在寻找应对措施
