### ISSUE TITLE
IP测速是用ping测的嘛？

### ISSUE THREAD

**Issue by mx4994** [GoodCoder666/GoogleTranslate_IPFinder#6]
用扫描结果的IP测试，都不能使用。可以ping通，但是tcp测443端口是不通的。

**Comment by GoodCoder666** [comment]
不是ping的。扫描方法是**给目标IP发送一个翻译的测试字符串**，返回了结果就视为可用IP。理论上测试结果应该是没有问题的，如果是真的有问题可以发个截屏。

还有你意思是扫描出来的IP测速不能通？应该没有这种情况吧
扫描和测速用的是同一个逻辑

**Comment by GoodCoder666** [comment]
你试试用把这个IP写入Hosts，看看谷歌翻译接口能不能用。如果能用的话端口是80还是443都不重要。

**Comment by GoodCoder666** [comment]
本地无法复现问题，可以尝试写入Hosts后执行`ipconfig /flushdns`（Windows）来刷新DNS缓存。

另外，**本项目的扫描/测速对象不是谷歌翻译UI网址`translate.google.com`而是API地址`translate.googleapis.com`**，一般配合浏览器翻译插件使用。

**Comment by yjd** [comment]
我用 https://hcfy.app/blog/2022/09/28/ggg 可用的ipv4数据入进去，测速。全部无效。
尝试用ping工具批量导入ping一下，能ping通写入hosts测试可以用于全网页翻译。
然后我就想看测速用什么方式，翻了代码，勉强看得懂一点点，找到
`TESTIP_FORMAT = 'https://{}/translate_a/single?client=gtx&sl=en&tl=fr&q=a'`
ip替换后放到浏览器请求，返回失败。
接着来这里找答案，结合上面聊天记录，看起来是谷歌在服务端设了只允许主机名访问，不能直接用ip访问。
因为写入hosts写入后，用
https://translate.googleapis.com/translate_a/single?client=gtx&sl=en&tl=fr&q=a
https://translate.googleapis.com/translate_a/element.js
能正常打开了

如果增加个ping模式。用原来的发包方式不行后，可以用ping模式试试。
@GoodCoder666
